# Generated by Django 5.0.3 on 2024-04-02 13:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_gym_trainer_gyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.gym'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.trainer'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='gyms',
            field=models.ManyToManyField(related_name='trainers', to='scheduler.gym'),
        ),
    ]
